name: Cypress Tests

on: [push]

jobs:
  ESLint-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ESLint
        uses: actions/checkout@v2
        with:
          start: npm run lint-check

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Write the cypress.env.json file 📝
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Run all Cyppress specs
        uses: cypress-io/github-action@v4.1.0
        with:
          spec: cypress/integration/specs/*.js
          browser: chrome
          headless: true
      - name: Cypress Test Reports
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: Test Reports
          path: cypress/reports/*.html