name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: Run changed Cypress specs first 🌲
        # it makes sense to run changed specs only if there are a few
        # otherwise just run all specs in the next step
        if: ${{ steps.list-changed-specs.outputs.specsN > 0 && steps.list-changed-specs.outputs.specsN < 5 }}
        uses: cypress-io/github-action@v4.1.0
        with:
          group: '1. Changed specs'
          spec: ${{ steps.list-changed-specs.outputs.specs }}
          headless: true
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
        with:
          group: '2. All Cypress specs'
          lint: npm run lint-check
          spec: cypress/integration/specs/*.js
          browser: chrome
          headless: true